name: ovmpk
channels: [conda-forge, bioconda]
dependencies:
  - python=3.10.*
  - numpy<2              # relax when mdtraj fully supports 2.x
  - pandas
  - scipy
  - matplotlib
  - biopython
  - openmm=8.*           # MD backend
  - pdbfixer>=1.9
  - mdanalysis>=2.4,<3
  - mdtraj>=1.9.9
  - rdkit=2023.*         # works with your current pipeline
  - openbabel>=3.1
  - propka
  - pdb2pqr
  - smina
  - pymol-open-source    # <â€” add this to keep PyMOL in the env
  - pytest
  - pip
  - pip:
      - dimorphite-dl
      - typer
      - pyyaml
      - requests
      - rcsb-api
